name: Build Workflow

# trigger
on: 
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    name: Build Laravel App
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{inputs.version}}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          composer install

      - name: Cache the Vendor
        uses: actions/cache@v4.0.2
        with:
          key: ${{ github.sha }}-php-vendor-cache
          path: ./vendor

      - name: Setup Env
        run: |
          cp .env.ci .env

      - name: Build the Application
        run: |
          php artisan key:generate