name: CI Workflow

# trigger
on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yaml
    with:
      version: "8.3"

  test:
    name: "Test"
    needs: [build]
    uses: ./.github/workflows/build.yaml
    with:
      version: "8.2"

  scan:
    name: "SonarCloud Scan"
    needs: [test]
    uses: ./.github/workflows/scan.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    name: "Build and Scan Docker Image"
    needs: [scan]
    uses: ./.github/workflows/docker.yaml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}