name: CI Workflow

# trigger
on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yaml
    with:
      version: "8.3"

  test:
    name: "Test"
    needs: [build]
    uses: ./.github/workflows/build.yaml
    with:
      version: "8.2"

  scan:
    name: "Scan"
    needs: [test]
    uses: ./.github/workflows/scan.yaml
    with:
      token: ${{ secrets.SONAR_TOKEN }}