name: CI Workflow

# trigger
on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  test:
    uses: ./.github/workflows/build.yaml

  dockerbuild:
    uses: ./.github/workflows/docker.yaml

