name: QA Workflow

# trigger
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  test:
    uses: ./.github/workflows/build.yaml

  scan:
    uses: ./.github/workflows/scan.yaml