name: QA Workflow

# trigger
on: workflow_dispatch

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yaml
    with:
      version: "8.3"

  test:
    name: "Test"
    uses: ./.github/workflows/build.yaml
    with:
      version: "8.2"

  scan:
    name: "Scan"
    uses: ./.github/workflows/scan.yaml
    with:
      token: ${{ secrets.SONAR_TOKEN }}