name: QA Workflow

# trigger
on:
  push:
   branches:
    - features/qa

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  test:
    need: [build]
    uses: ./.github/workflows/test.yaml

  scan:
    need: [test]
    uses: ./.github/workflows/scan.yaml