name: Scan workflow

#trigger
on: 
  workflow_call:

jobs:
  scan:
    name: Scan The Application
    runs-on: ubuntu-latest
    steps:
      - name: Sonar Cloud
        uses: sonarsource/sonarqube-scan-action@v2.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Trivy Scan in fs mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
