name: Scan workflow

#trigger
on: 
  workflow_call:
    inputs:
      token:
        required: true
        type: string

jobs:
  scan:
    name: Scan The Application
    runs-on: ubuntu-latest
    steps:
      - name: Sonar Cloud
        uses: sonarsource/sonarqube-scan-action@v2.2
        env:
          SONAR_TOKEN: ${{ inputs.token }}
