name: Scan workflow

#trigger
on: 
  workflow_call:
    inputs:
      secret_input:
        description: "sonar cloud secret key"
        required: true

jobs:
  sonarcloud:
    name: SonarCloud Scan The Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.3
        env:
          SONAR_TOKEN: ${{ inputs.secret_input }}
